using System.Collections.Generic;
using static GaugeOMatic.GameData.JobData;
using static GaugeOMatic.GameData.JobData.Job;
using static GaugeOMatic.GameData.JobData.Role;
using static GaugeOMatic.GameData.StatusRef.StatusActor;

namespace GaugeOMatic.GameData;

public partial class StatusRef
{
    public static readonly Dictionary<uint, StatusRef> StatusData = new()
    {
        #region Role/General

        { 2, new(2, Job.None, Target, Self, 1, Ranged) },                    // Stun,
        { 13, new(13, Job.None, Target, Self, 7, Ranged) },                  // Bind,
        { 14, new(14, Job.None, Target, Self, 10, Ranged) },                 // Heavy,
        { 49, new(49, Job.None, Self, Self, 30, All) },                      // Medicated,
        { 50, new(50, Job.None, Self, Self, 10, All) },                      // Sprint,
        { 84, new(84, Job.None, Self, Self, 20, Melee) },                    // Bloodbath,
        { 1191, new(1191, Job.None, Self, Self, 20, Tank) },                 // Rampart,
        { 1193, new(1193, Job.None, Target, Self, 10, Tank) },               // Reprisal,
        { 1195, new(1195, Job.None, Target, Self, 10, Melee) },              // Feint,
        { 1203, new(1203, Job.None, Target, Self, 10, Caster) },             // Addle,
        { 1204, new(1204, Job.None, Self, Self, 21, Caster | Healer) },      // Lucid Dreaming,
        { 1209, new(1209, Job.None, Self, Self, 6, Melee | Ranged | Tank) }, // Arm's Length,
        { 1250, new(1250, Job.None, Self, Self, 10, Melee) },                // True North,
        { 160, new(160, Job.None, Self, Self, 6, Caster | Healer) },         // Surecast,
        { 167, new(167, Job.None, Self, Self, 10, Caster | Healer) },        // Swiftcast,

        # endregion

        # region Melee

        { 102, new(102, PGL, Self, Self, 15) },   // Mantra,
        { 107, new(107, MNK, Self, Self, 30) },   // Opo-opo Form,
        { 108, new(108, MNK, Self, Self, 30) },   // Raptor Form,
        { 109, new(109, MNK, Self, Self, 30) },   // Coeurl Form,
        { 110, new(110, MNK, Self, Self, 20) },   // Perfect Balance,
        { 1179, new(1179, MNK, Self, Self, 10) }, // Riddle of Earth,
        { 1180, new(1180, MNK, Self, Self, 15) }, // Earth's Resolve,
        { 1181, new(1181, MNK, Self, Self, 20) }, // Riddle of Fire,
        { 1182, new(1182, MNK, Self, Self, 20) }, // Meditative Brotherhood,
        { 1185, new(1185, MNK, Self, Self, 15) }, // Brotherhood,
        { 2513, new(2513, MNK, Self, Self, 30) }, // Formless Fist,
        { 2514, new(2514, MNK, Self, Self, 5) },  // Six-sided Star,
        { 2687, new(2687, MNK, Self, Self, 15) }, // Riddle of Wind,
        { 3841, new(3841, MNK, Self, Self, 30) }, // Earth's Rumination,
        { 3842, new(3842, MNK, Self, Self, 15) }, // Wind's Rumination,
        { 3843, new(3843, MNK, Self, Self, 20) }, // Fire's Rumination,

        { 116, new(116, DRG, Self, Self, 5) },                            // Life Surge,
        { 786, new(786, DRG, Self, Self, 20) },                           // Battle Litany,
        { 1243, new(1243, DRG, Self, Self, 15) },                         // Dive Ready,
        { 1863, new(1863, DRG, Self, Self, 30) },                         // Draconian Fire,
        { 1864, new(1864, DRG, Self, Self, 20) },                         // Lance Charge,
        { 2719, new(2719, DRG, Target, Self, 24, seeAlso: [118, 1312]) }, // Chaotic Spring,
        { 118, new(2719, DRG, Target, Self, 24, seeAlso: [2719, 1312]) {HideFromDropdown = true}}, // Chaos Thrust
        { 1312, new(2719, DRG, Target, Self, 24, seeAlso: [118, 2719]) {HideFromDropdown = true}},
        { 2720, new(2720, DRG, Self, Self, 30) },                         // Power Surge,
        { 3844, new(3844, DRG, Self, Self, 20) },                         // Nastrond Ready,
        { 3845, new(3845, DRG, Self, Self, 30) },                         // Dragon's Flight,
        { 3846, new(3846, DRG, Self, Self, 20) },                         // Starcross REady,

        { 488, new(488, NIN, Self, Self, 19) },                              // Shade Shift,
        { 496, new(496, NIN, Self, Self, 6) },                               // Mudra,
        { 497, new(497, NIN, Self, Self, 15) },                              // Kassatsu,
        { 501, new(501, NIN, Self, Self, 18) },                              // Doton,
        { 502, new(502, NIN, Target, Self, 5) },                             // Doton Heavy,
        { 507, new(507, NIN, Self, Self, 20) },                              // Suiton,
        { 614, new(614, NIN, Self, Self, 0) },                               // Hidden,
        { 1186, new(1186, NIN, Self, Self, 6) },                             // Ten Chi Jin,
        { 1954, new(1954, NIN, Self, Self, 30) },                            // Bunshin,
        { 2689, new(2689, NIN, Self, Self, 30) },                            // Meisui,
        { 2690, new(2690, NIN, Self, Self, 30) },                            // Raiju Ready,
        { 2723, new(2723, NIN, Self, Self, 45) },                            // Phantom Kamaitachi Ready,
        { 3848, new(3848, NIN, Self, Self, 20) },                            // Shadow Walker,
        { 638, new(638, job: NIN, appliedTo: Target, appliedBy: Self, maxtime: 20, seeAlso: [3849]) },   // Mug,
        { 3849, new(3849, job: NIN, appliedTo: Target, appliedBy: Self, maxtime: 20, seeAlso: [638]) },  // Dokumori,
        { 3850, new(3850, NIN, Self, Self, 30) },                            // Higi,
        { 3851, new(3851, NIN, Self, Self, 30) },                            // Tenri Jindo Ready,
        { 3254, new(3254, job: NIN, appliedTo: Target, appliedBy: Self, maxtime: 15, seeAlso: [3906]) }, // Trick Attack,
        { 3906, new(3906, job: NIN, appliedTo: Target, appliedBy: Self, maxtime: 15, seeAlso: [3254]) }, // Kunai's Bane,

        { 1228, new(1228, SAM, Target, Self, 60) },                                                                // Higanbana,
        { 1231, new(1231, SAM, Self, Self, 15) },                                                                  // Meditate,
        { 1233, new(1233, SAM, Self, Self, 15) },                                                                  // Meikyo Shisui,
        { 1236, new(1236, SAM, Self, Self, 15) },                                                                  // Enhanced Enpi,
        { 1298, new(1298, SAM, Self, Self, 40) },                                                                  // Fugetsu,
        { 1299, new(1299, SAM, Self, Self, 40) },                                                                  // Fuka,
        { 2959, new(2959, SAM, Self, Self, 30) },                                                                  // Ogi Namikiri Ready,
        { 3852, new(3852, job: SAM, appliedTo: Self, appliedBy: Self, maxtime: 30, seeAlso: [4216, 4217, 4218]) { HideFromDropdown = true } }, // Tsubame-gaeshi Ready,
        { 4216, new(4216, job: SAM, appliedTo: Self, appliedBy: Self, maxtime: 30, seeAlso: [3852, 4217, 4218]) { HideFromDropdown = true } }, // 
        { 4217, new(4217, job: SAM, appliedTo: Self, appliedBy: Self, maxtime: 30, seeAlso: [3852, 4216, 4218]) { HideFromDropdown = true } }, // 
        { 4218, new(4218, job: SAM, appliedTo: Self, appliedBy: Self, maxtime: 30, seeAlso: [3852, 4216, 4217]) },                             // Tsubame-gaeshi,
        { 3853, new(3853, job: SAM, appliedTo: Self, appliedBy: Self, maxtime: 4, seeAlso: [1232]) },                                          // Tengetsu,
        { 1232, new(1232, job: SAM, appliedTo: Self, appliedBy: Self, maxtime: 4, seeAlso: [3853]) },                                            // Third Eye,
        { 3854, new(3854, SAM, Self, Self, 8) },                                                                   // Tengetsu's Foresight,
        { 3855, new(3855, SAM, Self, Self, 30) },                                                                  // Zanshin Ready,
        { 3856, new(3856, SAM, Self, Self, 30) },                                                                  // Tendo,

        { 2586, new(2586, RPR, Target, Self, 60) },                                                                    // Death's Design,
        { 2587, new(2587, RPR, Self, Self, 30) },                                                                      // Soul Reaver,
        { 2588, new(2588, RPR, Self, Self, 60) },                                                                      // Enhanced Gibbet,
        { 2589, new(2589, RPR, Self, Self, 60) },                                                                      // Enhanced Gallows,
        { 2590, new(2590, RPR, Self, Self, 30) },                                                                      // Enhanced Void Reaping,
        { 2591, new(2591, RPR, Self, Self, 30) },                                                                      // Enhanced Cross Reaping,
        { 2592, new(2592, RPR, Self, Self, 30) },                                                                      // Immortal Sacrifice,
        { 2593, new(2593, RPR, Self, Self, 30) },                                                                      // Enshrouded,
        { 2594, new(2594, RPR, Self, Self, 0) },                                                                       // Soulsow,
        { 2595, new(2595, RPR, Self, Self, 10) },                                                                      // Threshold,
        { 2597, new(2597, RPR, Self, Self, 5, Role.None, [2596]) },                             // Crest of Time Borrowed,
        { 2596, new(2596, RPR, Self, Self, 5, Role.None, [2597]) { HideFromDropdown = true } }, // Crest of Time Borrowed,
        { 2598, new(2598, RPR, Self, Self, 15) },                                                                      // Crest of Time Returned,
        { 2599, new(2599, RPR, Self, Self, 20) },                                                                      // Arcane Circle,
        { 2600, new(2600, RPR, Self, Self, 5) },                                                                       // Circle of Sacrifice,
        { 2845, new(2845, RPR, Self, Self, 20) },                                                                      // Enhanced Harpe,
        { 2972, new(2972, job: RPR, appliedTo: Self, appliedBy: Self, maxtime: 6, seeAlso: [2601]) },                                              // Bloodsown Circle,
        { 2601, new(2601, job: RPR, appliedTo: Self, appliedBy: Self, maxtime: 6, seeAlso: [2972]) { HideFromDropdown = true }},
        { 3857, new(3857, RPR, Self, Self, 30) }, // Oblatio,
        { 3858, new(3858, RPR, Self, Self, 30) }, // Executioner,
        { 3859, new(3859, RPR, Self, Self, 30) }, // Perfectio Occulta,
        { 3860, new(3860, RPR, Self, Self, 30) }, // Perfectio Parata,
        { 3905, new(3905, RPR, Self, Self, 30) }, // Ideal Host,

        { 3645, new(3645, VPR, Self, Self, 60) }, // Flankstung Venom,
        { 3646, new(3646, VPR, Self, Self, 60) }, // Flanksbane Venom,
        { 3647, new(3647, VPR, Self, Self, 60) }, // Hindstung Venom,
        { 3648, new(3648, VPR, Self, Self, 60) }, // Hindsbane Venom,
        { 3649, new(3649, VPR, Self, Self, 40) }, // Grimhunter's Venom,
        { 3650, new(3650, VPR, Self, Self, 40) }, // Grimskin's Venom,
        { 3657, new(3657, VPR, Self, Self, 30) }, // Hunter's Venom,
        { 3658, new(3658, VPR, Self, Self, 30) }, // Swiftskin's Venom,
        { 3659, new(3659, VPR, Self, Self, 30) }, // Fellhunter's Venom,
        { 3660, new(3660, VPR, Self, Self, 30) }, // Fellskin's Venom,
        { 3665, new(3665, VPR, Self, Self, 60) }, // Poised for Twinfang,
        { 3666, new(3666, VPR, Self, Self, 60) }, // Poised for Twinblood,
        { 3672, new(3672, VPR, Self, Self, 60) }, // Honed Steel,
        { 3668, new(3668, VPR, Self, Self, 40) }, // Hunter's Instinct,
        { 3669, new(3669, VPR, Self, Self, 40) }, // Swiftscaled,
        { 3671, new(3671, VPR, Self, Self, 30) }, // Ready to Reawaken,
        { 3670, new(3670, VPR, Self, Self, 30) }, // Reawakened,
        { 3772, new(3772, VPR, Self, Self, 60) }, // Honed Reavers,

        # endregion

        # region Ranged

        { 125, new(125, BRD, Self, Self, 20) },                                                     // Raging Strikes,
        { 128, new(128, BRD, Self, Self, 10) },                                                     // Barrage,
        { 141, new(141, BRD, Self, Self, 20) },                                                     // Battle Voice,
        { 866, new(866, BRD, Self, Self, 30) },                                                     // The Warden's Paean,
        { 1200, new(1200, job: BRD, appliedTo: Target, appliedBy: Self, maxtime: 45, seeAlso: [124]) },                         // Caustic Bite,
        { 124, new(124, job: BRD, appliedTo: Target, appliedBy: Self, maxtime: 45, seeAlso: [1200]) },                          // 
        { 1201, new(1201, job: BRD, appliedTo: Target, appliedBy: Self, maxtime: 45, seeAlso: [129]) },                         // Stormbite,
        { 129, new(129, job: BRD, appliedTo: Target, appliedBy: Self, maxtime: 45, seeAlso: [1201]) },                          // 
        { 1202, new(1202, BRD, Self, Self, 15) },                                                   // Nature's Minne,
        { 1932, new(1932, BRD, Self, Self, 10) },                                                   // Army's Muse,
        { 1934, new(1934, BRD, Self, Self, 15) },                                                   // Troubadour,
        { 2216, new(2216, BRD, Self, Self, 5) },                                                    // The Wanderer's Minuet,
        { 2217, new(2217, BRD, Self, Self, 5) },                                                    // Mage's Ballad,
        { 2218, new(2218, BRD, Self, Self, 5) },                                                    // Army's Paeon,
        { 2692, new(2692, BRD, Self, Self, 10) },                                                   // Blast Arrow Ready,
        { 2964, new(2964, job: BRD, appliedTo: Self, appliedBy: Self, maxtime: 20, seeAlso: [2722]) },                          // Radiant Finale,
        { 2722, new(2722, job: BRD, appliedTo: Self, appliedBy: Self, maxtime: 20, seeAlso: [2964]){HideFromDropdown = true} }, // 
        { 3002, new(3002, BRD, Self, Self, 30) },                                                   // Shadowbite Ready,
        { 3861, new(3861, job: BRD, appliedTo: Self, appliedBy: Self, maxtime: 30, seeAlso: [122]) },                           // Hawk's Eye,
        { 122, new(122, job: BRD, appliedTo: Self, appliedBy: Self, maxtime: 30, seeAlso: [3861]) },                            // 
        { 3862, new(3862, BRD, Self, Self, 30) },                                                   // Resonant Arrow Ready,
        { 3863, new(3863, BRD, Self, Self, 30) },                                                   // Radiant Encore Ready,

        { 851, new(851, MCH, Self, Self, 5) },                            // Reassembled,
        { 860, new(860, MCH, Target, Self, 5) },                          // Dismantled,
        { 1205, new(1205, MCH, Self, Self, 10) },                         // Flamethrower,
        { 1866, new(1866, MCH, Target, Self, 15) },                       // Bioblaster,
        { 1946, new(1946, job: MCH, appliedTo: Self, appliedBy: Self, maxtime: 10, seeAlso: [861]) }, // Wildfire,
        { 861, new(861, job: MCH, appliedTo: Self, appliedBy: Self, maxtime: 10, seeAlso: [1946]) },  // 
        { 1951, new(1951, MCH, Self, Self, 15) },                         // Tactician,
        { 2688, new(2688, MCH, Self, Self, 10) },                         // Overheated,
        { 3864, new(3864, MCH, Self, Self, 30) },                         // Hypercharged,
        { 3865, new(3865, MCH, Self, Self, 30) },                         // Excavator Ready,
        { 3866, new(3866, MCH, Self, Self, 30) },                         // Full Metal Machinist,

        { 1818, new(1818, DNC, Self, Self, 15) }, // Standard Step,
        { 1819, new(1819, DNC, Self, Self, 15) }, // Technical Step,
        { 1820, new(1820, DNC, Self, Self, 30) }, // Threefold Fan Dance,
        { 1821, new(1821, DNC, Self, Self, 60) }, // Standard Finish,
        { 1822, new(1822, DNC, Self, Self, 20) }, // Technical Finish,
        { 1825, new(1825, DNC, Self, Self, 20) }, // Devilment,
        { 1826, new(1826, DNC, Self, Self, 15) }, // Shield Samba,
        { 1827, new(1827, DNC, Self, Self, 15) }, // Improvisation,
        { 1847, new(1847, DNC, Self, Self, 60) }, // Esprit,
        { 2693, new(2693, DNC, Self, Self, 30) }, // Silken Symmetry,
        { 2694, new(2694, DNC, Self, Self, 30) }, // Silken Flow,
        { 2695, new(2695, DNC, Self, Self, 15) }, // Improvisation,
        { 2698, new(2698, DNC, Self, Self, 30) }, // Flourishing Finish,
        { 2699, new(2699, DNC, Self, Self, 30) }, // Fourfold Fan Dance,
        { 2700, new(2700, DNC, Self, Self, 20) }, // Flourishing Starfall,
        { 3017, new(3017, DNC, Self, Self, 30) }, // Flourishing Symmetry,
        { 3018, new(3018, DNC, Self, Self, 30) }, // Flourishing Flow,
        { 3867, new(3867, DNC, Self, Self, 30) }, // Last Dance Ready,
        { 3868, new(3868, DNC, Self, Self, 30) }, // Finishing Move Ready,
        { 3869, new(3869, DNC, Self, Self, 30) }, // Dance of the Dawn Ready,

        # endregion

        # region Caster

        { 161, new(161, job: BLM, appliedTo: Target, appliedBy: Self, maxtime: 24, seeAlso: [163]) { HideFromDropdown = true } },   // Thunder,
        { 163, new(163, job: BLM, appliedTo: Target, appliedBy: Self, maxtime: 24, seeAlso: [161]) },                               // 
        { 165, new(165, BLM, Self, Self, 30) },                                                         // Firestarter,
        { 168, new(168, BLM, Self, Self, 20) },                                                         // Manaward,
        { 737, new(737, BLM, Self, Self, 30) },                                                         // Ley Lines,
        { 738, new(738, BLM, Self, Self, 0) },                                                          // Circle of Power,
        { 1210, new(1210, BLM, Target, Self, 21) },                                                     // Thunder IV,
        { 1211, new(1211, BLM, Self, Self, 15) },                                                       // Triplecast,
        { 3870, new(3870, BLM, Self, Self, 30) },                                                       // Thunderhead,
        { 3871, new(3871, job: BLM, appliedTo: Target, appliedBy: Self, maxtime: 24, seeAlso: [3872]) },                            // High Thunder,
        { 3872, new(3872, job: BLM, appliedTo: Target, appliedBy: Self, maxtime: 24, seeAlso: [3871]){ HideFromDropdown = true } }, // 

        { 304, new(304, SMN, Self, Self, 0) },    // Aetherflow,
        { 1868, new(1868, SMN, Self, Self, 21) }, // Everlasting Flight,
        { 2701, new(2701, SMN, Self, Self, 60) }, // Further Ruin,
        { 2702, new(2702, SMN, Self, Self, 30) }, // Radiant Aegis,
        { 2703, new(2703, SMN, Self, Self, 30) }, // Searing Light,
        { 2704, new(2704, SMN, Self, Self, 30) }, // Rekindle,
        { 2705, new(2705, SMN, Self, Self, 15) }, // Undying Flame,
        { 2706, new(2706, SMN, Self, Self, 15) }, // Slipstream,
        { 2724, new(2724, SMN, Self, Self, 0) },  // Ifrit's Favor,
        { 2725, new(2725, SMN, Self, Self, 0) },  // Garuda's Favor,
        { 2853, new(2853, SMN, Self, Self, 0) },  // Titan's Favor,
        { 3873, new(3873, SMN, Self, Self, 30) }, // Ruby's Glimmer,
        { 3874, new(3874, SMN, Self, Self, 30) }, // Refulgent Lux,
        { 4400, new(4400, SMN, Self, Self, 0, seeAlso: [4403]) }, // Crimson Strike Ready,

        { 1234, new(1234, RDM, Self, Self, 30) }, // Verfire Ready,
        { 1235, new(1235, RDM, Self, Self, 30) }, // Verstone Ready,
        { 1238, new(1238, RDM, Self, Self, 20) }, // Acceleration,
        { 1239, new(1239, RDM, Self, Self, 20) }, // Embolden,
        { 1249, new(1249, RDM, Self, Self, 15) }, // Dualcast,
        { 1971, new(1971, RDM, Self, Self, 30) }, // Manafication,
        { 2707, new(2707, RDM, Self, Self, 10) }, // Magick Barrier,
        { 3875, new(3875, RDM, Self, Self, 15) }, // Magicked Swordplay,
        { 3876, new(3876, RDM, Self, Self, 30) }, // Thorned Flourish,
        { 3877, new(3877, RDM, Self, Self, 30) }, // Grand Impact Ready,
        { 3878, new(3878, RDM, Self, Self, 30) }, // Prefulgence Ready,

        { 3674, new(3674, PCT, Self, Self, 0) },  // Subtractive Palette,
        { 3675, new(3675, PCT, Self, Self, 30) }, // Aetherhues,
        { 3676, new(3676, PCT, Self, Self, 30) }, // Aetherhues II,
        { 3679, new(3679, PCT, Self, Self, 30) }, // Rainbow Bright,
        { 3680, new(3680, PCT, Self, Self, 30) }, // Hammer Time,
        { 3681, new(3681, PCT, Self, Self, 20) }, // Starstruck,
        { 3684, new(3684, PCT, Self, Self, 5) },  // Smudge,
        { 3685, new(3685, PCT, Self, Self, 20) }, // Starry Muse,
        { 3686, new(3686, PCT, Self, Self, 10) }, // Tempera Coat,
        { 3687, new(3687, PCT, Self, Self, 10) }, // Tempera Grassa,
        { 3688, new(3688, PCT, Self, Self, 30) }, // Hyperphantasia,
        { 3689, new(3689, PCT, Self, Self, 0) },  // Inspiration,
        { 3690, new(3690, PCT, Self, Self, 30) }, // Subtractive Spectrum,
        { 3691, new(3691, PCT, Self, Self, 0) },  // Monochrome Tones,

        # endregion

        # region Tank

        { 74, new(74, job: PLD, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [3829]) },           // Sentinel,
        { 76, new(76, PLD, Self, Self, 20) },                                  // Fight or Flight,
        { 77, new(77, PLD, Self, Self, 10) },                                  // Bulwark,
        { 79, new(79, PLD, Self, Self, 0) },                                   // Iron Will,
        { 82, new(82, PLD, Self, Self, 10) },                                  // Hallowed Ground,
        { 248, new(248, PLD, Target, Self, 15) },                              // Circle of Scorn,
        { 1175, new(1175, PLD, Self, Self, 18) },                              // Passage of Arms,
        { 1362, new(1362, GLA, Self, Self, 30) },                              // Divine Veil,
        { 1368, new(1368, GLA, Self, Self, 30) },                              // Requiescat,
        { 1902, new(1902, GLA, Self, Self, 30) },                              // Atonement Ready,
        { 2673, new(2673, GLA, Self, Self, 30) },                              // Divine Might,
        { 2674, new(2674, job: GLA, appliedTo: Self, appliedBy: Self, maxtime: 8, seeAlso: [728, 1856]) }, // Sheltron,
        { 728, new(728, job: GLA, appliedTo: Self, appliedBy: Self, maxtime: 8, seeAlso: [2674, 1856]) },  //
        { 1856, new(1856, job: GLA, appliedTo: Self, appliedBy: Self, maxtime: 8, seeAlso: [728, 2674]) {HideFromDropdown = true} },
        { 2675, new(2675, GLA, Self, Self, 4) },                        // Knight's Resolve,
        { 2676, new(2676, GLA, Self, Self, 12) },                       // Knight's Benediction,
        { 3019, new(3019, GLA, Self, Self, 30) },                       // Confiteor Ready,
        { 3827, new(3827, GLA, Self, Self, 30) },                       // Supplication Ready,
        { 3828, new(3828, GLA, Self, Self, 30) },                       // Sepulchre Ready,
        { 3829, new(3829, job: GLA, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [74])  }, // Guardian,
        { 3830, new(3830, GLA, Self, Self, 15)  },                      // Guardian's Will,
        { 3831, new(3831, GLA, Self, Self, 30) },                       // Blade of Honor Ready,
        { 3847, new(3847, GLA, Self, Self, 30) },                       // Goring Blade Ready,

        { 87, new(87, WAR, Self, Self, 10) },                            // Thrill of Battle,
        { 89, new(89, WAR, Self, Self, 15) },                            // Vengeance,
        { 91, new(91, WAR, Self, Self, 0) },                             // Defiance,
        { 409, new(409, WAR, Self, Self, 10) },                          // Holmgang,
        { 1177, new(1177, job: WAR, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [86]) }, // Inner Release,
        { 86, new(86, job: WAR, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [1177]) },   // 
        { 1457, new(1457, WAR, Self, Self, 30) },                        // Shake It Off,
        { 1897, new(1897, WAR, Self, Self, 30) },                        // Nascent Chaos,
        { 2108, new(2108, WAR, Self, Self, 15) },                        // Shake It Off (Over Time),
        { 2624, new(2624, WAR, Self, Self, 30) },                        // Primal Rend Ready,
        { 2663, new(2663, WAR, Self, Self, 15) },                        // Inner Strength,
        { 2677, new(2677, WAR, Self, Self, 60)  },                       // Surging Tempest
        { 735, new(735, job: WAR, appliedTo: Self, appliedBy: Self, maxtime: 8, seeAlso: [2678]) },  // Raw Intuition / Bloodwhetting,
        { 2678, new(2678, job: WAR, appliedTo: Self, appliedBy: Self, maxtime: 8, seeAlso: [735]) }, // 
        { 2679, new(2679, WAR, Self, Self, 4) },                         // Stem the Flow,
        { 2680, new(2680, WAR, Self, Self, 20) },                        // Stem the Tide,
        { 3832, new(3832, WAR, Self, Self, 15) },                        // Damnation,
        { 3833, new(3833, WAR, Self, Self, 30) },                        // Burgeoning Fury,
        { 3834, new(3834, WAR, Self, Self, 30) },                        // Primal Ruination Ready,
        { 3900, new(3900, WAR, Self, Self, 15) },                        // Primeval Impulse,
        { 3901, new(3901, WAR, Self, Self, 15) },                        // Wrathful,

        { 742, new(742, DRK, Self, Self, 15) },                                                        // Blood Weapon,
        { 743, new(743, DRK, Self, Self, 0) },                                                         // Grit,
        { 746, new(746, DRK, Self, Self, 10) },                                                        // Dark Mind,
        { 747, new(747, DRK, Self, Self, 15) },                                                        // Shadow Wall,
        { 749, new(749, DRK, Self, Self, 15) },                                                        // Salted Earth,
        { 810, new(810, DRK, Self, Self, 10) },                                                        // Living Dead,
        { 811, new(811, DRK, Self, Self, 10) },                                                        // Walking Dead,
        { 1178, new(1178, DRK, Self, Self, 7) },                                                       // Blackest Night,
        { 1894, new(1894, DRK, Self, Self, 15) },                                                      // Dark Missionary,
        { 1972, new(1972, job: DRK, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [3836]) },                             // Delirium,
        { 3836, new(3836, job: DRK, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [1972]) { HideFromDropdown = true } }, // 
        { 2682, new(2682, DRK, Self, Self, 10) },                                                      // Oblation,
        { 3255, new(3255, DRK, Self, Self, 10) },                                                      // Undead Rebirth,
        { 3835, new(3835, DRK, Self, Self, 15) },                                                      // Shadowed Vigil,
        { 3837, new(3837, DRK, Self, Self, 30) },                                                      // Scorn,
        { 3902, new(3902, DRK, Self, Self, 20) },                                                      // Vigilant,

        { 1831, new(1831, GNB, Self, Self, 20) },                          // No Mercy,
        { 1832, new(1832, GNB, Self, Self, 20) },                          // Camouflage,
        { 1833, new(1833, GNB, Self, Self, 0) },                           // Royal Guard,
        { 1834, new(1834, job: GNB, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [3838]) }, // Nebula,
        { 3838, new(3838, job: GNB, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [1834]) }, // 
        { 1835, new(1835, GNB, Self, Self, 18) },                          // Aurora,
        { 1836, new(1836, GNB, Self, Self, 10) },                          // Superbolide,
        { 1837, new(1837, GNB, Target, Self, 30) },                        // Sonic Break,
        { 1838, new(1838, GNB, Target, Self, 15) },                        // Bow Shock,
        { 1839, new(1839, GNB, Self, Self, 15) },                          // Heart of Light,
        { 1842, new(1842, GNB, Self, Self, 10) },                          // Ready to Rip,
        { 1843, new(1843, GNB, Self, Self, 10) },                          // Ready to Tear,
        { 1844, new(1844, GNB, Self, Self, 10) },                          // Ready to Gouge,
        { 1898, new(1898, GNB, Self, Self, 30) },                          // Brutal Shell,
        { 2683, new(2683, job: GNB, appliedTo: Self, appliedBy: Self, maxtime: 8, seeAlso: [1840]) },  // Heart of Corundum,
        { 1840, new(1840, job: GNB, appliedTo: Self, appliedBy: Self, maxtime: 8, seeAlso: [2683]) },  // 
        { 2684, new(2684, GNB, Self, Self, 4) },                           // Clarity of Corundum,
        { 2685, new(2685, GNB, Self, Self, 20) },                          // Catharsis of Corundum,
        { 2686, new(2686, GNB, Self, Self, 10) },                          // Ready to Blast,
        { 3839, new(3839, GNB, Self, Self, 10) },                          // Ready to Raze,
        { 3840, new(3840, GNB, Self, Self, 30) },                          // Ready to Reign,
        { 3886, new(3886, GNB, Self, Self, 30) },                          // Ready to Break,

        # endregion

        # region Healer

        { 3, new(3, WHM, Target, Self, 30) },                                         // Sleep,
        { 155, new(155, WHM, Self, Self, 15) },                                       // Freecure,
        { 157, new(157, WHM, Self, Self, 15) },                                       // Presence of Mind,
        { 158, new(158, WHM, Self, Self, 18) },                                       // Regen,
        { 1217, new(1217, WHM, Self, Self, 12) },                                     // Thin Air,
        { 1218, new(1218, WHM, Self, Self, 15) },                                     // Divine Benison,
        { 1219, new(1219, WHM, Self, Self, 10) },                                     // Confession,
        { 1871, new(1871, job: WHM, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [143, 144, 798]) }, // Dia,
        { 143, new(143, job: WHM, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [1871, 144, 798]) },  // 
        { 144, new(144, job: WHM, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [143, 1871, 798]) },  // 
        { 798, new(798, job: WHM, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [143, 144, 1871]) },  // 

        { 1872, new(1872, job: WHM, appliedTo: Self, appliedBy: Self, maxtime: 20, seeAlso: [1873]) },                           // Temperance,
        { 1873, new(1873, job: WHM, appliedTo: Self, appliedBy: Self, maxtime: 20, seeAlso: [1872]) {HideFromDropdown = true} }, // Temperance,
        { 1911, new(1911, job: WHM, appliedTo: Self, appliedBy: Self, maxtime: 24, seeAlso: [1912]) },                           // Asylum,
        { 1912, new(1912, job: WHM, appliedTo: Self, appliedBy: Self, maxtime: 24, seeAlso: [1911]) {HideFromDropdown = true} }, // 
        { 2708, new(2708, WHM, Self, Self, 8) },                                                     // Aquaveil,
        { 2709, new(2709, WHM, Self, Self, 20) },                                                    // Liturgy of the Bell,
        { 3879, new(3879, WHM, Self, Self, 30) },                                                    // Sacred Sight,
        { 150, new(150, job: WHM, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [3880]) },                             // Medica III,
        { 3880, new(3880, job: WHM, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [150]) },                            // Medica III,
        { 3903, new(3903, WHM, Self, Self, 10) },                                                    // Divine Caress,
        { 3881, new(3881, WHM, Self, Self, 30) },                                                    // Divine Grace,
        { 3904, new(3904, WHM, Self, Self, 15) },                                                    // Divine Aura,

        { 297, new(297, SCH, Self, Self, 30) },                                                     // Galvanize,
        { 315, new(315, SCH, Self, Self, 21) },                                                     // Whispering Dawn,
        { 317, new(317, SCH, Self, Self, 20) },                                                     // Fey Illumination,
        { 791, new(791, SCH, Self, Self, 30) },                                                     // Dissipation,
        { 792, new(792, SCH, Self, Self, 15) },                                                     // Emergency Tactics,
        { 1220, new(1220, SCH, Self, Self, 45) },                                                   // Excogitation,
        { 1221, new(1221, SCH, Target, Self, 15) },                                                 // Chain Stratagem,
        { 1223, new(1223, SCH, Self, Self, 60) },                                                   // Fey Union,
        { 1895, new(1895, job: SCH, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [189, 179]) },                    // Biolysis,
        { 189, new(189, job: SCH, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [1895, 179]) },                     // 
        { 179, new(179, job: SCH, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [189, 1895]) },                      //
        { 1896, new(1896, SCH, Self, Self, 15) },                                                   // Recitation,
        { 1917, new(1917, SCH, Self, Self, 30) },                                                   // Seraphic Veil,
        { 2710, new(2710, SCH, Self, Self, 10) },                                                   // Protraction,
        { 3882, new(3882, SCH, Self, Self, 30) },                                                   // Impact Imminent,
        { 3883, new(3883, SCH, Self, Self, 15) },                                                   // Baneful Impaction,
        { 3884, new(3884, job: SCH, appliedTo: Self, appliedBy: Self, maxtime: 20, seeAlso: [3885]) },                          // Seraphism,
        { 3885, new(3885, job: SCH, appliedTo: Self, appliedBy: Self, maxtime: 20, seeAlso: [3884]) {HideFromDropdown = true}}, // Seraphism,

        { 815, new(815, AST, Self, Self, 15) },                                                    // Enhanced Benefic II,
        { 841, new(841, job: AST, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [1403]) },                           // Lightspeed,
        { 1403, new(1403, job: AST, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [841]){HideFromDropdown = true} }, // Lightspeed,
        { 848, new(848, AST, Self, Self, 18) },                                                    // Collective Unconscious,
        { 849, new(849, AST, Self, Self, 5) },                                                     // Collective Unconscious,
        { 956, new(956, AST, Self, Self, 15) },                                                    // Wheel of Fortune,
        { 1224, new(1224, AST, Self, Self, 10) },                                                  // Earthly Dominance,
        { 1248, new(1248, AST, Self, Self, 10) },                                                  // Giant Dominance,
        { 1878, new(1878, AST, Self, Self, 15) },                                                  // Divination,
        { 1879, new(1879, AST, Self, Self, 15) },                                                  // Opposition,
        { 1881, new(1881, job: AST, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [838, 843]) },                   // Combust,
        { 838, new(838, job: AST, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [1881, 843]) },                    // 
        { 843, new(843, job: AST, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [838, 1881]) },                    // 
        { 1889, new(1889, AST, Self, Self, 30) },                                                  // Intersection,
        { 1890, new(1890, AST, Self, Self, 10) },                                                  // Horoscope,
        { 1891, new(1891, AST, Self, Self, 30) },                                                  // Horoscope Helios,
        { 1892, new(1892, AST, Self, Self, 20) },                                                  // Neutral Sect,
        { 1921, new(1921, AST, Self, Self, 30) },                                                  // Neutral Sect,
        { 2713, new(2713, AST, Self, Self, 30) },                                                  // Clarifying Draw,
        { 2714, new(2714, AST, Self, Self, 15) },                                                  // Harmony of Spirit,
        { 2715, new(2715, AST, Self, Self, 15) },                                                  // Harmony of Body,
        { 2717, new(2717, AST, Self, Self, 8) },                                                   // Exaltation,
        { 2718, new(2718, AST, Self, Self, 15) },                                                  // Macrocosmos,
        { 3887, new(3887, AST, Self, Self, 15) },                                                  // The Balance,
        { 3890, new(3890, AST, Self, Self, 15) },                                                  // The Bole,
        { 3888, new(3888, AST, Self, Self, 15) },                                                  // The Arrow,
        { 3889, new(3889, AST, Self, Self, 15) },                                                  // The Spear,
        { 3891, new(3891, AST, Self, Self, 15) },                                                  // The Ewer,
        { 3892, new(3892, AST, Self, Self, 30) },                                                  // The Spire,
        { 3893, new(3893, AST, Self, Self, 30) },                                                  // Divining,
        { 3894, new(3894, job: AST, appliedTo: Self, appliedBy: Self, maxtime: 30, seeAlso: [836]) },                          // Helios Conjunction,
        { 836, new(836, job: AST, appliedTo: Self, appliedBy: Self, maxtime: 30, seeAlso: [3894]) },                           // 
        { 3895, new(3895, AST, Self, Self, 30) },                                                  // Suntouched,
        { 3896, new(3896, AST, Self, Self, 15) },                                                  // Sun Sign,

        { 2604, new(2604, SGE, Self, Self, 60) },                                  // Kardia,
        { 2605, new(2605, SGE, Self, Self, 60) },                                  // Kardion,
        { 2606, new(2606, SGE, Self, Self, 0) },                                   // Eukrasia,
        { 2607, new(2607, SGE, Self, Self, 30) },                                  // Eukrasian Diagnosis,
        { 2609, new(2609, SGE, Self, Self, 30) },                                  // Eukrasian Prognosis,
        { 2610, new(2610, SGE, Self, Self, 15) },                                  // Soteria,
        { 2611, new(2611, SGE, Self, Self, 30) },                                  // Zoe,
        { 2612, new(2612, SGE, Self, Self, 15) },                                  // Haima,
        { 2613, new(2613, SGE, Self, Self, 15) },                                  // Panhaima,
        { 2616, new(2616, job: SGE, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [2614, 2615]) }, // Eukrasian Dosis,
        { 2614, new(2614, job: SGE, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [2616, 2615]) }, // 
        { 2615, new(2615, job: SGE, appliedTo: Target, appliedBy: Self, maxtime: 30, seeAlso: [2614, 2616]) }, // 
        { 2618, new(2618, SGE, Self, Self, 15) },                                  // Kerachole,
        { 2619, new(2619, SGE, Self, Self, 15) },                                  // Taurochole,
        { 2620, new(2620, job: SGE, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [2617]) },         // Physis,
        { 2617, new(2617, job: SGE, appliedTo: Self, appliedBy: Self, maxtime: 15, seeAlso: [2620]) },         // Physis,
        { 2621, new(2621, SGE, Self, Self, 10) },                                  // Autophysis,
        { 2622, new(2622, SGE, Self, Self, 10) },                                  // Krasis,
        { 2642, new(2642, SGE, Self, Self, 15) },                                  // Haimatinon,
        { 2643, new(2643, SGE, Self, Self, 15) },                                  // Panhaimatinon,
        { 2938, new(2938, SGE, Self, Self, 15) },                                  // Kerakeia,
        { 3003, new(3003, SGE, Self, Self, 20) },                                  // Holos,
        { 3365, new(3365, SGE, Self, Self, 30) },                                  // Holosakos,
        { 3897, new(3897, SGE, Target, Self, 30) },                                // Eukrasian Dyskrasia,
        { 3898, new(3898, SGE, Self, Self, 20) },                                  // Philosophia,
        { 3899, new(3899, SGE, Self, Self, 20) },                                  // Eudaimonia,

        #endregion
    };
}
